"use client";
import { useEffect, useState } from "react";
import { demoCard } from "@/lib/demo-card";

type CardState=typeof demoCard & {id?:string;status?:string};
export default function BuilderStudio(){
 const [card,setCard]=useState<CardState>(demoCard);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const set=(k:string,v:string)=>{setCard(c=>({...c,[k]:v}));setMessage("")};
 useEffect(()=>{fetch("/api/cards").then(r=>r.ok?r.json():null).then(data=>{const c=data?.cards?.[0];if(c)setCard(x=>({...x,id:c.id,status:c.status,slug:c.slug,name:c.display_name,title:c.title??"",company:c.company??"",bio:c.bio??""}));}).catch(()=>undefined)},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const payload={displayName:card.name,slug:card.slug,title:card.title,company:card.company,bio:card.bio,phones:card.phone?[card.phone]:[],emails:card.email?[card.email]:[],address:card.location?{city:card.location}:null,primaryCta:{label:card.primaryCtaLabel,url:card.primaryCtaUrl}};const url=card.id?`/api/cards/${card.id}`:"/api/cards";const r=await fetch(url,{method:card.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(r.ok){setCard(c=>({...c,id:data.card.id??c.id,status:data.card.status??c.status,slug:data.card.slug??c.slug}));setMessage("Draft saved to your account.");}else setMessage(data.error??"Unable to save draft.");setBusy(false);}
 async function publish(){if(!card.id)return setMessage("Save the draft before publishing.");setBusy(true);const r=await fetch(`/api/cards/${card.id}/publish`,{method:"POST"});const data=await r.json().catch(()=>({}));if(r.ok){setCard(c=>({...c,status:"published"}));setMessage("Card published.");}else setMessage(data.error??"Unable to publish.");setBusy(false);}
 return <section className="twoCol"><form className="card" onSubmit={save}><div className="eyebrow">CARD STUDIO · {card.status??"NEW"}</div><h2>Profile details</h2><div className="formGrid"><div className="field"><label>Full name</label><input value={card.name} onChange={e=>set("name",e.target.value)}/></div><div className="field"><label>Public slug</label><input value={card.slug} onChange={e=>set("slug",e.target.value)}/></div><div className="field"><label>Job title</label><input value={card.title} onChange={e=>set("title",e.target.value)}/></div><div className="field"><label>Company</label><input value={card.company} onChange={e=>set("company",e.target.value)}/></div><div className="field"><label>Phone</label><input value={card.phone} onChange={e=>set("phone",e.target.value)}/></div><div className="field"><label>Email</label><input value={card.email} onChange={e=>set("email",e.target.value)}/></div><div className="field full"><label>Location</label><input value={card.location} onChange={e=>set("location",e.target.value)}/></div><div className="field full"><label>Professional bio</label><textarea value={card.bio} onChange={e=>set("bio",e.target.value)}/></div></div><div className="actions"><button className="btn btnPrimary" disabled={busy} type="submit">{busy?"Working…":"Save draft"}</button><button className="btn" disabled={busy||!card.id} type="button" onClick={publish}>Publish</button>{card.status==="published"&&<a className="btn" href={`/u/${card.slug}`}>Open public card</a>}</div>{message&&<p className="success">{message}</p>}</form><aside className="previewShell"><div className="phone"><div className="avatar">FS</div><div className="eyebrow" style={{marginTop:18}}>LIVE PREVIEW</div><h2>{card.name}</h2><p>{card.title}<br/><strong>{card.company}</strong></p><div className="chips"><span className="chip">Emerald Network</span><span className="chip">{card.status??"draft"}</span></div><p>{card.bio}</p><a className="btn btnPrimary" href={`mailto:${card.email}`}>Connect now</a><div className="linkList"><span className="linkButton">{card.phone}</span><span className="linkButton">{card.email}</span><span className="linkButton">{card.location}</span></div></div></aside></section>
}
