import { NextResponse } from 'next/server';
import { currentUser } from '../../../../lib/auth';
import { query } from '../../../../lib/db';

type CardRow={id:string;slug:string;status:string;display_name:string;title:string|null;company:string|null;bio:string|null;phones:unknown;emails:unknown;address:unknown;primary_cta:unknown;updated_at:string};
async function owned(id:string,userId:string){const r=await query<CardRow>(`SELECT id,slug,status,display_name,title,company,bio,phones,emails,address,primary_cta,updated_at FROM cards WHERE id=$1 AND owner_user_id=$2 LIMIT 1`,[id,userId]);return r.rows[0];}
export async function GET(_:Request,{params}:{params:{id:string}}){const u=currentUser();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const card=await owned(params.id,u.id);return card?NextResponse.json({card}):NextResponse.json({error:'Not found'},{status:404});}
export async function PATCH(request:Request,{params}:{params:{id:string}}){const u=currentUser();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});if(!await owned(params.id,u.id))return NextResponse.json({error:'Not found'},{status:404});const b=await request.json().catch(()=>({}));const slug=typeof b.slug==='string'?b.slug.trim().toLowerCase().replace(/[^a-z0-9-]/g,''):undefined;if(slug!==undefined&&slug.length<3)return NextResponse.json({error:'Invalid slug'},{status:400});try{const r=await query<CardRow>(`UPDATE cards SET slug=COALESCE($3,slug),display_name=COALESCE($4,display_name),title=COALESCE($5,title),company=COALESCE($6,company),bio=COALESCE($7,bio),phones=COALESCE($8,phones),emails=COALESCE($9,emails),address=COALESCE($10,address),primary_cta=COALESCE($11,primary_cta),updated_at=now() WHERE id=$1 AND owner_user_id=$2 RETURNING id,slug,status,display_name,title,company,bio,phones,emails,address,primary_cta,updated_at`,[params.id,u.id,slug,b.displayName??null,b.title??null,b.company??null,b.bio??null,b.phones?JSON.stringify(b.phones):null,b.emails?JSON.stringify(b.emails):null,b.address?JSON.stringify(b.address):null,b.primaryCta?JSON.stringify(b.primaryCta):null]);return NextResponse.json({card:r.rows[0]});}catch(e:any){if(e?.code==='23505')return NextResponse.json({error:'Slug is already in use'},{status:409});throw e;}}
export async function DELETE(_:Request,{params}:{params:{id:string}}){const u=currentUser();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const r=await query(`DELETE FROM cards WHERE id=$1 AND owner_user_id=$2 RETURNING id`,[params.id,u.id]);return r.rowCount?NextResponse.json({ok:true}):NextResponse.json({error:'Not found'},{status:404});}
