"use client";
import { useEffect,useState } from "react";
type Member={user_id:string;email:string;display_name:string;role:string;status:string};
type Invitation={id:string;email:string;role:string;expires_at:string;accepted_at:string|null};
export default function OrgAdmin(){const [members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[email,setEmail]=useState(""),[role,setRole]=useState("member"),[msg,setMsg]=useState("");
 async function load(){const [m,i]=await Promise.all([fetch("/api/orgs/current/members"),fetch("/api/orgs/current/invitations")]);if(m.ok)setMembers((await m.json()).members);if(i.ok)setInvites((await i.json()).invitations)}
 useEffect(()=>{load().catch(()=>undefined)},[]);
 async function invite(){const r=await fetch("/api/orgs/current/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role})});const d=await r.json().catch(()=>({}));if(r.ok){setEmail("");setMsg("Invitation created. Share the invitation through your approved onboarding channel.");await load()}else setMsg(d.error??"Unable to invite member.")}
 async function change(userId:string,nextRole:string){const r=await fetch("/api/orgs/current/members",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,role:nextRole})});setMsg(r.ok?"Member role updated.":(await r.json().catch(()=>({}))).error??"Unable to update role.");if(r.ok)await load()}
 async function offboard(userId:string){if(!confirm("Deactivate this member and their organization cards?"))return;const r=await fetch("/api/orgs/current/members",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId})});setMsg(r.ok?"Member deactivated.":(await r.json().catch(()=>({}))).error??"Unable to deactivate member.");if(r.ok)await load()}
 return <div className="card"><div className="eyebrow">ADMIN CONTROLS</div><h2>Members & invitations</h2><div className="actions"><input aria-label="Invite email" placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select aria-label="Invitation role" value={role} onChange={e=>setRole(e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select><button className="btn btnPrimary" type="button" onClick={invite}>Invite</button></div>{msg&&<p className="success">{msg}</p>}<div className="dataTable">{members.map(m=><div className="dataRow" key={m.user_id}><strong>{m.display_name}<small> · {m.email}</small></strong><span>{m.role==="owner"?"Owner":<select aria-label={`Role for ${m.display_name}`} value={m.role} onChange={e=>change(m.user_id,e.target.value)} disabled={m.status!=="active"}><option value="member">Member</option><option value="admin">Admin</option></select>}</span><span className="chip">{m.status}</span>{m.role!=="owner"&&m.status==="active"?<button className="btn" type="button" onClick={()=>offboard(m.user_id)}>Deactivate</button>:<span/>}</div>)}</div><div className="eyebrow" style={{marginTop:18}}>INVITATIONS</div><div className="dataTable">{invites.length?invites.map(i=><div className="dataRow" key={i.id}><strong>{i.email}</strong><span>{i.role}</span><span className="chip">{i.accepted_at?"accepted":new Date(i.expires_at)<new Date()?"expired":"pending"}</span></div>):<p>No invitations yet.</p>}</div></div>}
