"use client";import { useEffect,useState } from "react";
type Endpoint={id:string;url:string;active:boolean;created_at:string};type Delivery={id:string;endpoint_id:string;url:string;event_name:string;status:string;attempts:number;last_http_status:number|null;last_error:string|null;created_at:string};
export default function WebhookAdmin(){const [eps,setEps]=useState<Endpoint[]>([]),[ds,setDs]=useState<Delivery[]>([]),[url,setUrl]=useState(""),[secret,setSecret]=useState(""),[msg,setMsg]=useState("");
async function load(){const [a,b]=await Promise.all([fetch("/api/webhooks"),fetch("/api/webhooks/deliveries")]);if(a.ok)setEps((await a.json()).endpoints);if(b.ok)setDs((await b.json()).deliveries)}
useEffect(()=>{load().catch(()=>undefined)},[]);
async function create(){const r=await fetch("/api/webhooks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const d=await r.json().catch(()=>({}));if(r.ok){setSecret(d.signingSecret);setUrl("");setMsg("Endpoint created. Store the signing secret now; it will not be shown again.");await load()}else setMsg(d.error??"Unable to create endpoint.")}
async function patch(e:Endpoint,active:boolean){const r=await fetch(`/api/webhooks/${e.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active})});setMsg(r.ok?"Endpoint updated.":(await r.json().catch(()=>({}))).error??"Update failed.");if(r.ok)await load()}
async function remove(id:string){if(!confirm("Delete this webhook endpoint and its delivery history?"))return;const r=await fetch(`/api/webhooks/${id}`,{method:"DELETE"});setMsg(r.ok?"Endpoint deleted.":(await r.json().catch(()=>({}))).error??"Delete failed.");if(r.ok)await load()}
async function retry(id:string){const r=await fetch(`/api/webhooks/deliveries/${id}/retry`,{method:"POST"});setMsg(r.ok?"Delivery queued for retry.":(await r.json().catch(()=>({}))).error??"Retry failed.");if(r.ok)await load()}
return <><section className="card"><div className="eyebrow">WEBHOOK ADMIN</div><h1>Integrations</h1><p>Manage signed outbound endpoints and delivery recovery.</p><div className="actions"><input aria-label="Webhook URL" placeholder="https://crm.example.com/webhooks/digi-ip" value={url} onChange={e=>setUrl(e.target.value)}/><button className="btn btnPrimary" onClick={create}>Add endpoint</button></div>{msg&&<p>{msg}</p>}{secret&&<div className="card"><strong>One-time signing secret</strong><code style={{display:"block",wordBreak:"break-all"}}>{secret}</code></div>}<div className="dataTable">{eps.map(e=><div className="dataRow" key={e.id}><strong>{e.url}</strong><span className="chip">{e.active?"active":"inactive"}</span><button className="btn" onClick={()=>patch(e,!e.active)}>{e.active?"Disable":"Enable"}</button><button className="btn" onClick={()=>remove(e.id)}>Delete</button></div>)}</div></section><section className="card" style={{marginTop:18}}><h2>Recent deliveries</h2><div className="dataTable">{ds.map(d=><div className="dataRow" key={d.id}><strong>{d.event_name}</strong><span className="chip">{d.status}</span><span>{d.attempts} attempts{d.last_http_status?` · HTTP ${d.last_http_status}`:""}</span>{["failed","dead_letter"].includes(d.status)?<button className="btn" onClick={()=>retry(d.id)}>Retry</button>:<span/>}</div>)}</div></section></>}
